#pragma once

static const char web_index_html[] = 
"<!doctype html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <link rel=\"stylesheet\" href=\"/static/styles.css\">\n"
"  <title>Panel Dashboard</title>\n"
"</head>\n"
"<body>\n"
"  <nav>\n"
"    <a href=\"/dashboard\" class=\"active\">Dashboard</a>\n"
"    <a href=\"/config\">Configure</a>\n"
"    <a href=\"/diag\">Diagnostics</a>\n"
"  </nav>\n"
"  <main>\n"
"    <h1 id=\"panel-name\">Loading...</h1>\n"
"    <div id=\"status\"></div>\n"
"    <div id=\"banks\"></div>\n"
"  </main>\n"
"  <script src=\"/static/app.js\"></script>\n"
"</body>\n"
"</html>\n"
"\n";

static const char web_config_html[] = 
"<!doctype html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <link rel=\"stylesheet\" href=\"/static/styles.css\">\n"
"  <title>Panel Configuration</title>\n"
"</head>\n"
"<body>\n"
"  <nav>\n"
"    <a href=\"/dashboard\">Dashboard</a>\n"
"    <a href=\"/config\" class=\"active\">Configure</a>\n"
"    <a href=\"/diag\">Diagnostics</a>\n"
"  </nav>\n"
"  <main>\n"
"    <h1>Configuration</h1>\n"
"    <div id=\"alert\"></div>\n"
"    <form id=\"config-form\">\n"
"      <div class=\"form-group\">\n"
"        <label>Panel Name</label>\n"
"        <input name=\"panel_name\" placeholder=\"e.g., Sanctuary Lights\">\n"
"      </div>\n"
"      <h3>MQTT Settings</h3>\n"
"      <div class=\"form-group\">\n"
"        <label>Broker IP Address</label>\n"
"        <input name=\"mqtt.broker_ip\" placeholder=\"192.168.1.100\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label>Broker Port</label>\n"
"        <input name=\"mqtt.port\" placeholder=\"1883\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label>Username (optional)</label>\n"
"        <input name=\"mqtt.username\" placeholder=\"user\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label>Password (optional)</label>\n"
"        <input name=\"mqtt.password\" type=\"password\" placeholder=\"password\">\n"
"      </div>\n"
"      <h3>WiFi Settings</h3>\n"
"      <div class=\"form-group\">\n"
"        <label>WiFi SSID</label>\n"
"        <input name=\"wifi.ssid\" placeholder=\"Network Name\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label>WiFi Password</label>\n"
"        <input name=\"wifi.password\" type=\"password\" placeholder=\"Password\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label><input type=\"checkbox\" name=\"wifi.use_dhcp\" id=\"use_dhcp\"> Use DHCP (Automatic IP)</label>\n"
"      </div>\n"
"      <fieldset id=\"static-ip-fields\" style=\"display:none\">\n"
"        <legend>Static IP Configuration</legend>\n"
"        <div class=\"form-group\">\n"
"          <label>IP Address</label>\n"
"          <input name=\"wifi.static_ip\" placeholder=\"192.168.1.50\">\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <label>Netmask</label>\n"
"          <input name=\"wifi.static_netmask\" placeholder=\"255.255.255.0\">\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <label>Gateway</label>\n"
"          <input name=\"wifi.static_gateway\" placeholder=\"192.168.1.1\">\n"
"        </div>\n"
"      </fieldset>\n"
"      <button type=\"submit\">Save Configuration</button>\n"
"    </form>\n"
"    <div style=\"margin-top:24px;padding-top:24px;border-top:1px solid #ddd;\">\n"
"      <h3>Device Management</h3>\n"
"      <button id=\"restart-btn\" type=\"button\" style=\"background:#e74c3c;\">Restart Device</button>\n"
"    </div>\n"
"  </main>\n"
"  <script src=\"/static/app.js\"></script>\n"
"</body>\n"
"</html>\n"
"\n";

static const char web_diag_html[] = 
"<!doctype html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <link rel=\"stylesheet\" href=\"/static/styles.css\">\n"
"  <title>Diagnostics</title>\n"
"</head>\n"
"<body>\n"
"  <nav>\n"
"    <a href=\"/dashboard\">Dashboard</a>\n"
"    <a href=\"/config\">Configure</a>\n"
"    <a href=\"/diag\" class=\"active\">Diagnostics</a>\n"
"  </nav>\n"
"  <main>\n"
"    <h1>System Diagnostics</h1>\n"
"    <button onclick=\"location.reload()\">Refresh</button>\n"
"    <pre id=\"diag\">Loading...</pre>\n"
"  </main>\n"
"  <script src=\"/static/app.js\"></script>\n"
"</body>\n"
"</html>\n"
"\n";

static const char web_styles_css[] = 
"*{margin:0;padding:0;box-sizing:border-box}\n"
"body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:#f5f5f5;color:#333}\n"
"nav{background:linear-gradient(135deg,#2c3e50 0%,#34495e 100%);padding:12px 20px;display:flex;gap:20px;box-shadow:0 2px 8px rgba(0,0,0,0.1)}\n"
"nav a{color:#fff;text-decoration:none;padding:8px 16px;border-radius:4px;transition:background 0.3s}\n"
"nav a:hover{background:rgba(255,255,255,0.1)}\n"
"nav a.active{background:#3498db}\n"
"main{max-width:900px;margin:0 auto;padding:24px 20px}\n"
"h1{color:#2c3e50;margin-bottom:24px;font-size:28px}\n"
"h3{color:#34495e;margin-top:16px;margin-bottom:12px;font-size:18px}\n"
".form-group{margin-bottom:16px}\n"
"label{display:block;margin-bottom:6px;font-weight:500;color:#555}\n"
"input,textarea{padding:10px 12px;width:100%;border:1px solid #ddd;border-radius:4px;font-family:inherit;font-size:14px;transition:border-color 0.3s}\n"
"input[type=\"checkbox\"]{width:auto;margin-right:8px}\n"
"input:focus,textarea:focus{outline:none;border-color:#3498db;box-shadow:0 0 0 3px rgba(52,152,219,0.1)}\n"
"button{padding:10px 20px;background:#3498db;color:#fff;border:none;border-radius:4px;font-size:14px;font-weight:600;cursor:pointer;transition:background 0.3s;margin-top:12px}\n"
"button:hover{background:#2980b9}\n"
"button:active{transform:scale(0.98)}\n"
"fieldset{border:1px solid #ddd;padding:12px;border-radius:4px;margin:12px 0}\n"
"legend{padding:0 8px;font-weight:600;color:#34495e}\n"
".status{display:flex;gap:12px;margin-bottom:20px;flex-wrap:wrap}\n"
".status-item{display:flex;align-items:center;gap:6px;padding:8px 12px;background:#fff;border-radius:4px;box-shadow:0 1px 3px rgba(0,0,0,0.1)}\n"
".status-dot{width:10px;height:10px;border-radius:50%;display:inline-block}\n"
".status-dot.online{background:#27ae60}\n"
".status-dot.offline{background:#e74c3c}\n"
".bank-section{background:#fff;padding:16px;border-radius:4px;margin-bottom:16px;box-shadow:0 1px 4px rgba(0,0,0,0.1)}\n"
".button-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin-top:12px}\n"
".button-item{padding:12px;background:#f9f9f9;border:1px solid #e0e0e0;border-radius:4px;font-size:13px}\n"
".button-item strong{display:block;color:#2c3e50;margin-bottom:4px}\n"
"pre{background:#f5f5f5;padding:16px;border-radius:4px;overflow-x:auto;font-size:12px;line-height:1.4}\n"
".alert{padding:12px 16px;border-radius:4px;margin-bottom:16px}\n"
".alert.success{background:#d4edda;border:1px solid #c3e6cb;color:#155724}\n"
".alert.error{background:#f8d7da;border:1px solid #f5c6cb;color:#721c24}\n"
"\n";

static const char web_app_js[] = 
"async function fetchJson(path){\n"
"  const res = await fetch(path);\n"
"  if(!res.ok) throw new Error(res.statusText);\n"
"  return res.json();\n"
"}\n"
"\n"
"async function initDashboard(){\n"
"  try{\n"
"    const [cfg,diag] = await Promise.all([fetchJson('/api/config'),fetchJson('/api/diag')]);\n"
"    document.getElementById('panel-name').textContent = cfg.panel_name || 'Panel';\n"
"    \n"
"    let statusHtml = '<div class=\"status\">';\n"
"    statusHtml += `<div class=\"status-item\"><span class=\"status-dot ${diag.mqtt_connected?'online':'offline'}\"></span> MQTT: ${diag.mqtt_connected?'Online':'Offline'}</div>`;\n"
"    statusHtml += `<div class=\"status-item\"><span class=\"status-dot ${diag.eth_connected?'online':'offline'}\"></span> ETH: ${diag.eth_connected?'Online':'Offline'}</div>`;\n"
"    statusHtml += `<div class=\"status-item\"><span class=\"status-dot ${diag.wifi_connected?'online':'offline'}\"></span> Wi-Fi: ${diag.wifi_connected?'Online':'Offline'}</div>`;\n"
"    statusHtml += '</div>';\n"
"    document.getElementById('status')?.remove();\n"
"    const statusDiv = document.createElement('div');\n"
"    statusDiv.id = 'status';\n"
"    statusDiv.innerHTML = statusHtml;\n"
"    document.querySelector('main').insertBefore(statusDiv, document.querySelector('main').firstChild);\n"
"    \n"
"    const banksDiv = document.getElementById('banks');\n"
"    banksDiv.innerHTML = '';\n"
"    (cfg.banks||[]).forEach((b,idx)=>{\n"
"      const bd = document.createElement('div');\n"
"      bd.className = 'bank-section';\n"
"      bd.innerHTML = `<h3>Bank ${idx+1}: ${b.bank_name}</h3><div class=\"button-list\">`;\n"
"      b.buttons.forEach((btn,i)=> {\n"
"        bd.querySelector('.button-list').innerHTML += `<div class=\"button-item\"><strong>${i+1}. ${btn.display_name}</strong>${btn.mqtt_topic}</div>`;\n"
"      });\n"
"      bd.querySelector('.button-list').innerHTML += '</div>';\n"
"      banksDiv.appendChild(bd);\n"
"    });\n"
"  }catch(e){console.error(e)}\n"
"}\n"
"\n"
"async function initConfig(){\n"
"  try{\n"
"    const cfg = await fetchJson('/api/config');\n"
"    const form = document.getElementById('config-form');\n"
"    form.elements['panel_name'].value = cfg.panel_name || '';\n"
"    form.elements['mqtt.broker_ip'].value = cfg.mqtt.broker_ip || '';\n"
"    form.elements['mqtt.port'].value = cfg.mqtt.port || '';\n"
"    form.elements['mqtt.username'].value = cfg.mqtt.username || '';\n"
"    form.elements['mqtt.password'].value = cfg.mqtt.password || '';\n"
"    \n"
"    form.elements['wifi.ssid'].value = cfg.wifi.ssid || '';\n"
"    form.elements['wifi.password'].value = cfg.wifi.password || '';\n"
"    form.elements['wifi.use_dhcp'].checked = cfg.wifi.use_dhcp;\n"
"    form.elements['wifi.static_ip'].value = cfg.wifi.static_ip || '';\n"
"    form.elements['wifi.static_netmask'].value = cfg.wifi.static_netmask || '';\n"
"    form.elements['wifi.static_gateway'].value = cfg.wifi.static_gateway || '';\n"
"    \n"
"    // Toggle static IP fields visibility\n"
"    const staticFields = document.getElementById('static-ip-fields');\n"
"    const dhcpCheckbox = document.getElementById('use_dhcp');\n"
"    const updateStaticFieldsVisibility = () => {\n"
"      staticFields.style.display = dhcpCheckbox.checked ? 'none' : 'block';\n"
"    };\n"
"    dhcpCheckbox.addEventListener('change', updateStaticFieldsVisibility);\n"
"    updateStaticFieldsVisibility(); // Set initial state\n"
"\n"
"    form.addEventListener('submit', async (ev)=>{\n"
"      ev.preventDefault();\n"
"      const alertDiv = document.getElementById('alert');\n"
"      try {\n"
"        const body = {\n"
"          panel_name: form.elements['panel_name'].value,\n"
"          mqtt: {\n"
"            broker_ip: form.elements['mqtt.broker_ip'].value,\n"
"            port: form.elements['mqtt.port'].value,\n"
"            username: form.elements['mqtt.username'].value,\n"
"            password: form.elements['mqtt.password'].value\n"
"          },\n"
"          wifi: {\n"
"            ssid: form.elements['wifi.ssid'].value,\n"
"            password: form.elements['wifi.password'].value,\n"
"            use_dhcp: form.elements['wifi.use_dhcp'].checked,\n"
"            static_ip: form.elements['wifi.static_ip'].value,\n"
"            static_netmask: form.elements['wifi.static_netmask'].value,\n"
"            static_gateway: form.elements['wifi.static_gateway'].value\n"
"          }\n"
"        };\n"
"        const res = await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});\n"
"        if(res.ok){\n"
"          alertDiv.innerHTML = '<div class=\"alert success\">✓ Configuration saved successfully</div>';\n"
"          setTimeout(() => alertDiv.innerHTML = '', 3000);\n"
"        }else{\n"
"          alertDiv.innerHTML = '<div class=\"alert error\">✗ Failed to save configuration</div>';\n"
"        }\n"
"      }catch(e){\n"
"        alertDiv.innerHTML = '<div class=\"alert error\">✗ Error: '+e.message+'</div>';\n"
"      }\n"
"    });\n"
"    \n"
"    const restartBtn = document.getElementById('restart-btn');\n"
"    if(restartBtn){\n"
"      restartBtn.addEventListener('click', async ()=>{\n"
"        const alertDiv = document.getElementById('alert');\n"
"        if(!confirm('Are you sure you want to restart the device?')) return;\n"
"        try {\n"
"          const res = await fetch('/api/reboot', {method: 'POST', headers: {'Content-Type': 'application/json'}});\n"
"          if(res.ok){\n"
"            alertDiv.innerHTML = '<div class=\"alert success\">✓ Device rebooting...</div>';\n"
"            setTimeout(() => {\n"
"              alertDiv.innerHTML = '<div class=\"alert error\">Connection lost (device is restarting)</div>';\n"
"            }, 1000);\n"
"          }else{\n"
"            alertDiv.innerHTML = '<div class=\"alert error\">✗ Failed to reboot device</div>';\n"
"          }\n"
"        }catch(e){\n"
"          alertDiv.innerHTML = '<div class=\"alert error\">✗ Error: '+e.message+'</div>';\n"
"        }\n"
"      });\n"
"    }\n"
"  }catch(e){console.error(e)}\n"
"}\n"
"\n"
"async function initDiag(){\n"
"  try{\n"
"    const d = await fetchJson('/api/diag');\n"
"    document.getElementById('diag').textContent = JSON.stringify(d,null,2);\n"
"  }catch(e){console.error(e)}\n"
"}\n"
"\n"
"// Router: call init based on path\n"
"if (location.pathname === '/' || location.pathname === '/dashboard') initDashboard();\n"
"if (location.pathname === '/config') initConfig();\n"
"if (location.pathname === '/diag') initDiag();\n"
"\n";

