#pragma once

static const char web_index_html[] = 
"<!doctype html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <link rel=\"stylesheet\" href=\"/static/styles.css\">\n"
"  <title>Panel Dashboard</title>\n"
"</head>\n"
"<body>\n"
"  <nav>\n"
"    <a href=\"/dashboard\" class=\"active\">Dashboard</a>\n"
"    <a href=\"/config\">Configure</a>\n"
"    <a href=\"/banks\">Banks & Buttons</a>\n"
"    <a href=\"/diag\">Diagnostics</a>\n"
"  </nav>\n"
"  <main>\n"
"    <h1 id=\"panel-name\">Loading...</h1>\n"
"    <div id=\"status\"></div>\n"
"    <div id=\"banks\"></div>\n"
"  </main>\n"
"  <script src=\"/static/app.js\"></script>\n"
"</body>\n"
"</html>\n"
"\n";

static const char web_config_html[] = 
"<!doctype html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <link rel=\"stylesheet\" href=\"/static/styles.css\">\n"
"  <title>Panel Configuration</title>\n"
"</head>\n"
"<body>\n"
"  <nav>\n"
"    <a href=\"/dashboard\">Dashboard</a>\n"
"    <a href=\"/config\" class=\"active\">Configure</a>\n"
"    <a href=\"/banks\">Banks & Buttons</a>\n"
"    <a href=\"/diag\">Diagnostics</a>\n"
"  </nav>\n"
"  <main>\n"
"    <h1>Configuration</h1>\n"
"    <div id=\"alert\"></div>\n"
"    <form id=\"config-form\">\n"
"      <div class=\"form-group\">\n"
"        <label>Panel Name</label>\n"
"        <input name=\"panel_name\" placeholder=\"e.g., Sanctuary Lights\">\n"
"      </div>\n"
"      <h3>MQTT Settings</h3>\n"
"      <div class=\"form-group\">\n"
"        <label>Broker IP Address</label>\n"
"        <input name=\"mqtt.broker_ip\" placeholder=\"192.168.1.100\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label>Broker Port</label>\n"
"        <input name=\"mqtt.port\" placeholder=\"1883\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label>Username (optional)</label>\n"
"        <input name=\"mqtt.username\" placeholder=\"user\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label>Password (optional)</label>\n"
"        <input name=\"mqtt.password\" type=\"password\" placeholder=\"password\">\n"
"      </div>\n"
"      <h3>WiFi Settings</h3>\n"
"      <div class=\"form-group\">\n"
"        <label>WiFi SSID</label>\n"
"        <input name=\"wifi.ssid\" placeholder=\"Network Name\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label>WiFi Password</label>\n"
"        <input name=\"wifi.password\" type=\"password\" placeholder=\"Password\">\n"
"      </div>\n"
"      <div class=\"form-group\">\n"
"        <label><input type=\"checkbox\" name=\"wifi.use_dhcp\" id=\"use_dhcp\"> Use DHCP (Automatic IP)</label>\n"
"      </div>\n"
"      <fieldset id=\"static-ip-fields\" style=\"display:none\">\n"
"        <legend>Static IP Configuration</legend>\n"
"        <div class=\"form-group\">\n"
"          <label>IP Address</label>\n"
"          <input name=\"wifi.static_ip\" placeholder=\"192.168.1.50\">\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <label>Netmask</label>\n"
"          <input name=\"wifi.static_netmask\" placeholder=\"255.255.255.0\">\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <label>Gateway</label>\n"
"          <input name=\"wifi.static_gateway\" placeholder=\"192.168.1.1\">\n"
"        </div>\n"
"      </fieldset>\n"
"      <button type=\"submit\">Save Configuration</button>\n"
"    </form>\n"
"    <div style=\"margin-top:24px;padding-top:24px;border-top:1px solid #ddd;\">\n"
"      <h3>Device Management</h3>\n"
"      <button id=\"restart-btn\" type=\"button\" style=\"background:#e74c3c;\">Restart Device</button>\n"
"    </div>\n"
"  </main>\n"
"  <script src=\"/static/app.js\"></script>\n"
"</body>\n"
"</html>\n"
"\n";

static const char web_banks_html[] = 
"<!doctype html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <link rel=\"stylesheet\" href=\"/static/styles.css\">\n"
"  <title>Banks & Buttons</title>\n"
"</head>\n"
"<body>\n"
"  <nav>\n"
"    <a href=\"/dashboard\">Dashboard</a>\n"
"    <a href=\"/config\">Configure</a>\n"
"    <a href=\"/banks\" class=\"active\">Banks & Buttons</a>\n"
"    <a href=\"/diag\">Diagnostics</a>\n"
"  </nav>\n"
"  <main>\n"
"    <h1>Banks & Buttons Configuration</h1>\n"
"    <div id=\"alert\"></div>\n"
"    \n"
"    <div class=\"config-section\">\n"
"      <h3>Panel Name</h3>\n"
"      <div class=\"form-group\">\n"
"        <input id=\"panel-name-input\" type=\"text\" placeholder=\"Panel name\" maxlength=\"16\">\n"
"        <button type=\"button\" id=\"save-panel-name-btn\" class=\"btn-small\">Save</button>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div class=\"config-section\">\n"
"      <h3>Number of Banks</h3>\n"
"      <div style=\"display:flex;gap:12px;align-items:center;\">\n"
"        <input id=\"num-banks-input\" type=\"number\" min=\"1\" max=\"8\" style=\"width:80px;\">\n"
"        <button type=\"button\" id=\"update-banks-btn\" class=\"btn-small\">Update</button>\n"
"        <span id=\"bank-count-info\" style=\"color:#666;font-size:14px;\"></span>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div id=\"banks-container\" style=\"margin-top:24px;\">\n"
"      <!-- Banks will be populated here -->\n"
"    </div>\n"
"\n"
"    <div style=\"margin-top:24px;text-align:center;\">\n"
"      <button id=\"save-all-btn\" type=\"button\" style=\"padding:12px 24px;font-size:16px;\">Save All Changes</button>\n"
"    </div>\n"
"  </main>\n"
"  <script src=\"/static/app.js\"></script>\n"
"  <script>\n"
"    async function initBanks() {\n"
"      try {\n"
"        const cfg = await fetchJson('/api/config');\n"
"        renderBanksUI(cfg);\n"
"        \n"
"        document.getElementById('panel-name-input').value = cfg.panel_name || '';\n"
"        document.getElementById('num-banks-input').value = cfg.num_banks;\n"
"        \n"
"        document.getElementById('save-panel-name-btn').addEventListener('click', async () => {\n"
"          const newName = document.getElementById('panel-name-input').value;\n"
"          cfg.panel_name = newName;\n"
"          await saveConfig(cfg);\n"
"        });\n"
"        \n"
"        document.getElementById('update-banks-btn').addEventListener('click', async () => {\n"
"          const newNum = parseInt(document.getElementById('num-banks-input').value) || 1;\n"
"          if (newNum < 1 || newNum > 8) {\n"
"            showAlert('Number of banks must be between 1 and 8', 'error');\n"
"            return;\n"
"          }\n"
"          if (newNum < cfg.num_banks) {\n"
"            if (!confirm(`Reducing banks from ${cfg.num_banks} to ${newNum}. Banks ${newNum + 1}-${cfg.num_banks} will be lost. Continue?`)) {\n"
"              document.getElementById('num-banks-input').value = cfg.num_banks;\n"
"              return;\n"
"            }\n"
"            cfg.banks.splice(newNum); // truncate\n"
"          } else if (newNum > cfg.num_banks) {\n"
"            // initialize new banks with defaults\n"
"            for (let nb = cfg.num_banks; nb < newNum; nb++) {\n"
"              cfg.banks[nb] = createDefaultBank(nb+1);\n"
"            }\n"
"          }\n"
"          cfg.num_banks = newNum;\n"
"          renderBanksUI(cfg);\n"
"        });\n"
"        \n"
"        document.getElementById('save-all-btn').addEventListener('click', async () => {\n"
"          await saveConfig(cfg);\n"
"        });\n"
"        \n"
"      } catch (e) {\n"
"        console.error(e);\n"
"        showAlert('Failed to load configuration: ' + e.message, 'error');\n"
"      }\n"
"    }\n"
"    \n"
"    function renderBanksUI(cfg) {\n"
"      const container = document.getElementById('banks-container');\n"
"      container.innerHTML = '';\n"
"      \n"
"      for (let b = 0; b < cfg.num_banks; b++) {\n"
"        const bank = cfg.banks[b];\n"
"        const bankDiv = document.createElement('div');\n"
"        bankDiv.className = 'bank-card';\n"
"        bankDiv.innerHTML = `\n"
"          <div class=\"bank-header\">\n"
"            <div>\n"
"              <label>Bank ${b + 1} Name:</label>\n"
"              <input type=\"text\" class=\"bank-name\" maxlength=\"16\" value=\"${bank.bank_name || ''}\">\n"
"            </div>\n"
"          </div>\n"
"          <div class=\"buttons-grid\">\n"
"        `;\n"
"        \n"
"        for (let i = 0; i < cfg.banks[b].buttons.length; i++) {\n"
"            const btn = cfg.banks[b].buttons[i];\n"
"          bankDiv.innerHTML += `\n"
"            <div class=\"button-card\">\n"
"              <div class=\"button-header\">\n"
"                  <input type=\"text\" class=\"btn-name\" placeholder=\"Button name\" maxlength=\"16\" value=\"${btn.display_name || ''}\">\n"
"                  <button class=\"btn-small copy-btn\" title=\"Copy button\">Copy</button>\n"
"                  <button class=\"btn-small paste-btn\" title=\"Paste button\">Paste</button>\n"
"              </div>\n"
"              <div class=\"form-group\">\n"
"                <label>MQTT Topic</label>\n"
"                <input type=\"text\" class=\"btn-topic\" placeholder=\"e.g., scene/zone/state\" maxlength=\"63\" value=\"${btn.mqtt_topic || ''}\">\n"
"              </div>\n"
"              <div class=\"form-group\">\n"
"                <label>Button Type</label>\n"
"                <select class=\"btn-type\">\n"
"                  <option value=\"0\" ${btn.type === 0 ? 'selected' : ''}>Toggle</option>\n"
"                  <option value=\"1\" ${btn.type === 1 ? 'selected' : ''}>Momentary</option>\n"
"                  <option value=\"2\" ${btn.type === 2 ? 'selected' : ''}>Radio</option>\n"
"                </select>\n"
"              </div>\n"
"              <div class=\"form-group ${btn.type === 2 ? '' : 'hidden'}\">\n"
"                <label>Radio Group</label>\n"
"                <input type=\"number\" class=\"btn-radio-group\" min=\"0\" max=\"255\" value=\"${btn.radio_group || 0}\">\n"
"              </div>\n"
"              <div class=\"color-section\">\n"
"                <label>LED Colors</label>\n"
"                <div style=\"display:flex;gap:12px;\">\n"
"                  <div>\n"
"                    <small>On</small>\n"
"                    <input type=\"color\" class=\"btn-color-on\" value=\"#${toHex(btn.color_on || [0,0,0])}\">\n"
"                  </div>\n"
"                  <div>\n"
"                    <small>Off</small>\n"
"                    <input type=\"color\" class=\"btn-color-off\" value=\"#${toHex(btn.color_off || [0,0,0])}\">\n"
"                  </div>\n"
"                </div>\n"
"              </div>\n"
"            </div>\n"
"          `;\n"
"        }\n"
"        \n"
"        bankDiv.innerHTML += '</div>';\n"
"        container.appendChild(bankDiv);\n"
"      }\n"
"      \n"
"      // Wire up dynamic events\n"
"      document.querySelectorAll('.btn-type').forEach((select, idx) => {\n"
"        select.addEventListener('change', (e) => {\n"
"          const radioGroupField = e.target.closest('.button-card').querySelector('.btn-radio-group').parentElement;\n"
"          radioGroupField.classList.toggle('hidden', e.target.value !== '2');\n"
"        });\n"
"      });\n"
"\n"
"      // Copy/paste logic\n"
"      let copyBuffer = null;\n"
"      document.querySelectorAll('.copy-btn').forEach(btn => {\n"
"        btn.addEventListener('click', (e) => {\n"
"          const card = e.target.closest('.button-card');\n"
"          copyBuffer = collectButtonCard(card);\n"
"          showAlert('Button copied to clipboard', 'success');\n"
"        });\n"
"      });\n"
"      document.querySelectorAll('.paste-btn').forEach(btn => {\n"
"        btn.addEventListener('click', async (e) => {\n"
"          if (!copyBuffer) { showAlert('Nothing to paste', 'error'); return; }\n"
"          const card = e.target.closest('.button-card');\n"
"          applyButtonCard(card, copyBuffer);\n"
"          showAlert('Pasted settings to button (save to persist)', 'success');\n"
"        });\n"
"      });\n"
"    }\n"
"    \n"
"    async function saveConfig(cfg) {\n"
"      // Collect all values from the UI\n"
"      const panelNameInput = document.getElementById('panel-name-input');\n"
"      cfg.panel_name = panelNameInput.value;\n"
"      \n"
"      document.querySelectorAll('.bank-card').forEach((bankDiv, b) => {\n"
"        const bankNameInput = bankDiv.querySelector('.bank-name');\n"
"        cfg.banks[b].bank_name = bankNameInput.value;\n"
"        \n"
"        bankDiv.querySelectorAll('.button-card').forEach((btnDiv, i) => {\n"
"          cfg.banks[b].buttons[i].display_name = btnDiv.querySelector('.btn-name').value;\n"
"          cfg.banks[b].buttons[i].mqtt_topic = btnDiv.querySelector('.btn-topic').value;\n"
"          cfg.banks[b].buttons[i].type = parseInt(btnDiv.querySelector('.btn-type').value);\n"
"          cfg.banks[b].buttons[i].radio_group = parseInt(btnDiv.querySelector('.btn-radio-group').value);\n"
"          \n"
"          const onColor = btnDiv.querySelector('.btn-color-on').value;\n"
"          const offColor = btnDiv.querySelector('.btn-color-off').value;\n"
"          cfg.banks[b].buttons[i].color_on = hexToRgb(onColor);\n"
"          cfg.banks[b].buttons[i].color_off = hexToRgb(offColor);\n"
"        });\n"
"      });\n"
"      \n"
"      try {\n"
"        const res = await fetch('/api/config', {\n"
"          method: 'POST',\n"
"          headers: { 'Content-Type': 'application/json' },\n"
"          body: JSON.stringify(cfg)\n"
"        });\n"
"        if (res.ok) {\n"
"          showAlert('✓ All configuration saved successfully', 'success');\n"
"        } else {\n"
"          showAlert('✗ Failed to save configuration', 'error');\n"
"        }\n"
"      } catch (e) {\n"
"        showAlert('✗ Error: ' + e.message, 'error');\n"
"      }\n"
"    }\n"
"    \n"
"    function toHex(rgb) {\n"
"      return rgb.map(x => (x || 0).toString(16).padStart(2, '0')).join('');\n"
"    }\n"
"    \n"
"    function hexToRgb(hex) {\n"
"      const result = /^#?([a-f\\d]{2})([a-f\\d]{2})([a-f\\d]{2})$/i.exec(hex);\n"
"      return result ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)] : [0, 0, 0];\n"
"    }\n"
"\n"
"    function createDefaultBank(index) {\n"
"      const bank = { bank_name: `Bank ${index}`, buttons: [] };\n"
"      for (let i = 0; i < 4; i++) {\n"
"        bank.buttons.push({\n"
"          display_name: `Btn ${i+1}`,\n"
"          mqtt_topic: `panel/bank${index}/btn${i+1}`,\n"
"          type: 0,\n"
"          radio_group: 0,\n"
"          color_on: [0,255,0],\n"
"          color_off: [255,0,0]\n"
"        });\n"
"      }\n"
"      return bank;\n"
"    }\n"
"\n"
"    function collectButtonCard(card) {\n"
"      return {\n"
"        display_name: card.querySelector('.btn-name').value,\n"
"        mqtt_topic: card.querySelector('.btn-topic').value,\n"
"        type: parseInt(card.querySelector('.btn-type').value),\n"
"        radio_group: parseInt(card.querySelector('.btn-radio-group')?.value || 0),\n"
"        color_on: hexToRgb(card.querySelector('.btn-color-on').value),\n"
"        color_off: hexToRgb(card.querySelector('.btn-color-off').value)\n"
"      };\n"
"    }\n"
"\n"
"    function applyButtonCard(card, data) {\n"
"      card.querySelector('.btn-name').value = data.display_name || '';\n"
"      card.querySelector('.btn-topic').value = data.mqtt_topic || '';\n"
"      card.querySelector('.btn-type').value = String(data.type || 0);\n"
"      const rg = card.querySelector('.btn-radio-group'); if (rg) rg.value = data.radio_group || 0;\n"
"      card.querySelector('.btn-color-on').value = `#${toHex(data.color_on || [0,0,0])}`;\n"
"      card.querySelector('.btn-color-off').value = `#${toHex(data.color_off || [0,0,0])}`;\n"
"    }\n"
"    \n"
"    function showAlert(msg, type) {\n"
"      const alertDiv = document.getElementById('alert');\n"
"      const className = type === 'error' ? 'alert error' : 'alert success';\n"
"      alertDiv.innerHTML = `<div class=\"${className}\">${msg}</div>`;\n"
"      if (type === 'success') {\n"
"        setTimeout(() => alertDiv.innerHTML = '', 3000);\n"
"      }\n"
"    }\n"
"    \n"
"    if (location.pathname === '/banks') initBanks();\n"
"  </script>\n"
"</body>\n"
"</html>\n"
"\n";

static const char web_diag_html[] = 
"<!doctype html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <link rel=\"stylesheet\" href=\"/static/styles.css\">\n"
"  <title>Diagnostics</title>\n"
"</head>\n"
"<body>\n"
"  <nav>\n"
"    <a href=\"/dashboard\">Dashboard</a>\n"
"    <a href=\"/config\">Configure</a>\n"
"    <a href=\"/banks\">Banks & Buttons</a>\n"
"    <a href=\"/diag\" class=\"active\">Diagnostics</a>\n"
"  </nav>\n"
"  <main>\n"
"    <h1>System Diagnostics</h1>\n"
"    <button onclick=\"location.reload()\">Refresh</button>\n"
"    <pre id=\"diag\">Loading...</pre>\n"
"  </main>\n"
"  <script src=\"/static/app.js\"></script>\n"
"</body>\n"
"</html>\n"
"\n";

static const char web_styles_css[] = 
"*{margin:0;padding:0;box-sizing:border-box}\n"
"body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:#f5f5f5;color:#333}\n"
"nav{background:linear-gradient(135deg,#2c3e50 0%,#34495e 100%);padding:12px 20px;display:flex;gap:20px;box-shadow:0 2px 8px rgba(0,0,0,0.1);flex-wrap:wrap}\n"
"nav a{color:#fff;text-decoration:none;padding:8px 16px;border-radius:4px;transition:background 0.3s}\n"
"nav a:hover{background:rgba(255,255,255,0.1)}\n"
"nav a.active{background:#3498db}\n"
"main{max-width:1000px;margin:0 auto;padding:24px 20px}\n"
"h1{color:#2c3e50;margin-bottom:24px;font-size:28px}\n"
"h3{color:#34495e;margin-top:16px;margin-bottom:12px;font-size:18px}\n"
".form-group{margin-bottom:16px}\n"
"label{display:block;margin-bottom:6px;font-weight:500;color:#555}\n"
"input,textarea,select{padding:10px 12px;width:100%;border:1px solid #ddd;border-radius:4px;font-family:inherit;font-size:14px;transition:border-color 0.3s;background:#fff}\n"
"input[type=\"checkbox\"]{width:auto;margin-right:8px}\n"
"input[type=\"color\"]{cursor:pointer;height:44px}\n"
"input[type=\"number\"]{width:100%}\n"
".btn-small{padding:8px 14px;font-size:12px;margin-top:0;margin-left:8px}\n"
"input[type=\"checkbox\"]{width:auto;margin-right:8px}\n"
"input:focus,textarea:focus{outline:none;border-color:#3498db;box-shadow:0 0 0 3px rgba(52,152,219,0.1)}\n"
"button{padding:10px 20px;background:#3498db;color:#fff;border:none;border-radius:4px;font-size:14px;font-weight:600;cursor:pointer;transition:background 0.3s;margin-top:12px}\n"
"button:hover{background:#2980b9}\n"
"button:active{transform:scale(0.98)}\n"
"fieldset{border:1px solid #ddd;padding:12px;border-radius:4px;margin:12px 0}\n"
"legend{padding:0 8px;font-weight:600;color:#34495e}\n"
".status{display:flex;gap:12px;margin-bottom:20px;flex-wrap:wrap}\n"
".status-item{display:flex;align-items:center;gap:6px;padding:8px 12px;background:#fff;border-radius:4px;box-shadow:0 1px 3px rgba(0,0,0,0.1)}\n"
".status-dot{width:10px;height:10px;border-radius:50%;display:inline-block}\n"
".status-dot.online{background:#27ae60}\n"
".status-dot.offline{background:#e74c3c}\n"
".bank-section{background:#fff;padding:16px;border-radius:4px;margin-bottom:16px;box-shadow:0 1px 4px rgba(0,0,0,0.1)}\n"
".button-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin-top:12px}\n"
".button-item{padding:12px;background:#f9f9f9;border:1px solid #e0e0e0;border-radius:4px;font-size:13px}\n"
".button-item strong{display:block;color:#2c3e50;margin-bottom:4px}\n"
"pre{background:#f5f5f5;padding:16px;border-radius:4px;overflow-x:auto;font-size:12px;line-height:1.4}\n"
".alert{padding:12px 16px;border-radius:4px;margin-bottom:16px}\n"
".alert.success{background:#d4edda;border:1px solid #c3e6cb;color:#155724}\n"
".alert.error{background:#f8d7da;border:1px solid #f5c6cb;color:#721c24}\n"
".config-section{background:#fff;padding:16px;border-radius:4px;margin-bottom:20px;box-shadow:0 1px 3px rgba(0,0,0,0.08)}\n"
".bank-card{background:#fff;padding:20px;border-radius:6px;margin-bottom:20px;box-shadow:0 2px 6px rgba(0,0,0,0.1);border-left:4px solid #3498db}\n"
".bank-header{margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid #e0e0e0}\n"
".bank-header input{font-size:16px;font-weight:600;color:#2c3e50}\n"
".buttons-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px;margin-top:16px}\n"
".button-card{background:#f8f9fa;padding:14px;border-radius:5px;border:1px solid #e0e0e0;transition:box-shadow 0.2s}\n"
".button-card:hover{box-shadow:0 2px 8px rgba(0,0,0,0.1)}\n"
".button-header{margin-bottom:12px}\n"
".btn-name{font-weight:600;font-size:15px;color:#2c3e50 !important}\n"
".btn-topic{font-size:13px;font-family:'Courier New',monospace;background:#f0f0f0}\n"
".btn-type{width:100%}\n"
".btn-radio-group{width:100%}\n"
".color-section{margin-top:12px;padding-top:12px;border-top:1px solid #d0d0d0}\n"
".color-section label{margin-bottom:8px}\n"
".color-section small{display:block;font-size:12px;color:#666;margin-bottom:4px;font-weight:500}\n"
".hidden{display:none !important}\n"
"\n";

static const char web_app_js[] = 
"async function fetchJson(path){\n"
"  const res = await fetch(path);\n"
"  if(!res.ok) throw new Error(res.statusText);\n"
"  return res.json();\n"
"}\n"
"\n"
"async function initDashboard(){\n"
"  try{\n"
"    const [cfg,diag] = await Promise.all([fetchJson('/api/config'),fetchJson('/api/diag')]);\n"
"    document.getElementById('panel-name').textContent = cfg.panel_name || 'Panel';\n"
"    \n"
"    let statusHtml = '<div class=\"status\">';\n"
"    statusHtml += `<div class=\"status-item\"><span class=\"status-dot ${diag.mqtt_connected?'online':'offline'}\"></span> MQTT: ${diag.mqtt_connected?'Online':'Offline'}</div>`;\n"
"    statusHtml += `<div class=\"status-item\"><span class=\"status-dot ${diag.eth_connected?'online':'offline'}\"></span> ETH: ${diag.eth_connected?'Online':'Offline'}</div>`;\n"
"    statusHtml += `<div class=\"status-item\"><span class=\"status-dot ${diag.wifi_connected?'online':'offline'}\"></span> Wi-Fi: ${diag.wifi_connected?'Online':'Offline'}</div>`;\n"
"    statusHtml += '</div>';\n"
"    document.getElementById('status')?.remove();\n"
"    const statusDiv = document.createElement('div');\n"
"    statusDiv.id = 'status';\n"
"    statusDiv.innerHTML = statusHtml;\n"
"    document.querySelector('main').insertBefore(statusDiv, document.querySelector('main').firstChild);\n"
"    \n"
"    const banksDiv = document.getElementById('banks');\n"
"    banksDiv.innerHTML = '';\n"
"    (cfg.banks||[]).forEach((b,idx)=>{\n"
"      const bd = document.createElement('div');\n"
"      bd.className = 'bank-section';\n"
"      bd.innerHTML = `<h3>Bank ${idx+1}: ${b.bank_name}</h3><div class=\"button-list\">`;\n"
"      b.buttons.forEach((btn,i)=> {\n"
"        bd.querySelector('.button-list').innerHTML += `<div class=\"button-item\"><strong>${i+1}. ${btn.display_name}</strong>${btn.mqtt_topic}</div>`;\n"
"      });\n"
"      bd.querySelector('.button-list').innerHTML += '</div>';\n"
"      banksDiv.appendChild(bd);\n"
"    });\n"
"  }catch(e){console.error(e)}\n"
"}\n"
"\n"
"async function initConfig(){\n"
"  try{\n"
"    const cfg = await fetchJson('/api/config');\n"
"    const form = document.getElementById('config-form');\n"
"    form.elements['panel_name'].value = cfg.panel_name || '';\n"
"    form.elements['mqtt.broker_ip'].value = cfg.mqtt.broker_ip || '';\n"
"    form.elements['mqtt.port'].value = cfg.mqtt.port || '';\n"
"    form.elements['mqtt.username'].value = cfg.mqtt.username || '';\n"
"    form.elements['mqtt.password'].value = cfg.mqtt.password || '';\n"
"    \n"
"    form.elements['wifi.ssid'].value = cfg.wifi.ssid || '';\n"
"    form.elements['wifi.password'].value = cfg.wifi.password || '';\n"
"    form.elements['wifi.use_dhcp'].checked = cfg.wifi.use_dhcp;\n"
"    form.elements['wifi.static_ip'].value = cfg.wifi.static_ip || '';\n"
"    form.elements['wifi.static_netmask'].value = cfg.wifi.static_netmask || '';\n"
"    form.elements['wifi.static_gateway'].value = cfg.wifi.static_gateway || '';\n"
"    \n"
"    // Toggle static IP fields visibility\n"
"    const staticFields = document.getElementById('static-ip-fields');\n"
"    const dhcpCheckbox = document.getElementById('use_dhcp');\n"
"    const updateStaticFieldsVisibility = () => {\n"
"      staticFields.style.display = dhcpCheckbox.checked ? 'none' : 'block';\n"
"    };\n"
"    dhcpCheckbox.addEventListener('change', updateStaticFieldsVisibility);\n"
"    updateStaticFieldsVisibility(); // Set initial state\n"
"\n"
"    form.addEventListener('submit', async (ev)=>{\n"
"      ev.preventDefault();\n"
"      const alertDiv = document.getElementById('alert');\n"
"      try {\n"
"        const body = {\n"
"          panel_name: form.elements['panel_name'].value,\n"
"          mqtt: {\n"
"            broker_ip: form.elements['mqtt.broker_ip'].value,\n"
"            port: form.elements['mqtt.port'].value,\n"
"            username: form.elements['mqtt.username'].value,\n"
"            password: form.elements['mqtt.password'].value\n"
"          },\n"
"          wifi: {\n"
"            ssid: form.elements['wifi.ssid'].value,\n"
"            password: form.elements['wifi.password'].value,\n"
"            use_dhcp: form.elements['wifi.use_dhcp'].checked,\n"
"            static_ip: form.elements['wifi.static_ip'].value,\n"
"            static_netmask: form.elements['wifi.static_netmask'].value,\n"
"            static_gateway: form.elements['wifi.static_gateway'].value\n"
"          }\n"
"        };\n"
"        const res = await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});\n"
"        if(res.ok){\n"
"          alertDiv.innerHTML = '<div class=\"alert success\">✓ Configuration saved successfully</div>';\n"
"          setTimeout(() => alertDiv.innerHTML = '', 3000);\n"
"        }else{\n"
"          alertDiv.innerHTML = '<div class=\"alert error\">✗ Failed to save configuration</div>';\n"
"        }\n"
"      }catch(e){\n"
"        alertDiv.innerHTML = '<div class=\"alert error\">✗ Error: '+e.message+'</div>';\n"
"      }\n"
"    });\n"
"    \n"
"    const restartBtn = document.getElementById('restart-btn');\n"
"    if(restartBtn){\n"
"      restartBtn.addEventListener('click', async ()=>{\n"
"        const alertDiv = document.getElementById('alert');\n"
"        if(!confirm('Are you sure you want to restart the device?')) return;\n"
"        try {\n"
"          const res = await fetch('/api/reboot', {method: 'POST', headers: {'Content-Type': 'application/json'}});\n"
"          if(res.ok){\n"
"            alertDiv.innerHTML = '<div class=\"alert success\">✓ Device rebooting...</div>';\n"
"            setTimeout(() => {\n"
"              alertDiv.innerHTML = '<div class=\"alert error\">Connection lost (device is restarting)</div>';\n"
"            }, 1000);\n"
"          }else{\n"
"            alertDiv.innerHTML = '<div class=\"alert error\">✗ Failed to reboot device</div>';\n"
"          }\n"
"        }catch(e){\n"
"          alertDiv.innerHTML = '<div class=\"alert error\">✗ Error: '+e.message+'</div>';\n"
"        }\n"
"      });\n"
"    }\n"
"  }catch(e){console.error(e)}\n"
"}\n"
"\n"
"async function initDiag(){\n"
"  try{\n"
"    const d = await fetchJson('/api/diag');\n"
"    document.getElementById('diag').textContent = JSON.stringify(d,null,2);\n"
"  }catch(e){console.error(e)}\n"
"}\n"
"\n"
"// Router: call init based on path\n"
"if (location.pathname === '/' || location.pathname === '/dashboard') initDashboard();\n"
"if (location.pathname === '/config') initConfig();\n"
"if (location.pathname === '/diag') initDiag();\n"
"\n";

